# Generated by Django 4.2.1 on 2023-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moive',
            name='img',
            field=models.ImageField(default='dddd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
