# Generated by Django 4.2.1 on 2023-09-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_moive_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moive',
            new_name='Movie',
        ),
    ]
